#!/bin/sh
#
# This file is part of HiGFXback

test $# -eq 1 || { echo Usage: $0 \"package name\"; exit 1; }

PATCHES=$(realpath ${PATCHES:-../patches})

BACKEND=`dirname $1`

CANONICAL_PACKAGE=`basename $1 | tr '[:upper:]' '[:lower:]'`

PATCH=`grep -l /$CANONICAL_PACKAGE-build.pc $PATCHES/$BACKEND/*.patch`

test -n "$PATCH" || { echo $CANONICAL_PACKAGE: package not found; exit 1; }

PACKAGE=`sed -n 's/^Name: //p' $PATCH`-`sed -n 's/^Version: //p' $PATCH`

REQUIRES=`sed -n 's/^REQUIRES="\(.*\)"/\1/p' $PATCHES/$BACKEND/$PACKAGE.patch`
test -z "$REQUIRES" || PKG_CONFIG_PATH=/$BACKEND/share/pkgconfig pkg-config --exists --print-errors $REQUIRES || exit 1

NEW_FILES=$(awk '/^---/{ oldfile = $2 }/^\+\+\+/{ newfile = $2 }/^@@ -0,0/{ print newfile }' $PATCHES/$BACKEND/$PACKAGE.patch)
for FILE in $NEW_FILES; do test -f $FILE && rm -f $FILE; done

pkg-get $PATCHES/$BACKEND/$PACKAGE.patch
( cd $PACKAGE && patch -p1 < $PATCHES/$BACKEND/$PACKAGE.patch )
( cd $PACKAGE && sh $PATCHES/$BACKEND/$PACKAGE.patch )
