#!/bin/sh

if [ $# != 2 ]; then
  echo Usage: $0 \"backend\" \"implementation\"
  exit 1
fi

test -f /$1/lib/lib${2}EGL.so.* && ln -sf `basename /$1/lib/lib${2}EGL.so.*` /$1/lib/libEGL.so.1
test -f /$1/lib/lib${2}GL.so.* && ln -sf `basename /$1/lib/lib${2}GL.so.*` /$1/lib/libGL.so.1
test -f /$1/lib/lib${2}GLESv1_CM.so.* && ln -sf `basename /$1/lib/lib${2}GLESv1_CM.so.*` /$1/lib/libGLESv1_CM.so.1
test -f /$1/lib/lib${2}GLESv2.so.* && ln -sf `basename /$1/lib/lib${2}GLESv2.so.*` /$1/lib/libGLESv2.so.2
