#!/bin/sh
#
# This file is part of HiGFXback

if [ $# != 2 ]; then
  echo Usage: $0 \"backend\" \"implementation\"
  exit 1
fi

test -f /$1/lib/lib${2}EGL.so.1 && ln -sf lib${2}EGL.so.1 /$1/lib/libEGL.so.1
test -f /$1/lib/lib${2}GL.so.1 && ln -sf lib${2}GL.so.1 /$1/lib/libGL.so.1
test -f /$1/lib/lib${2}GLESv1_CM.so.1 && ln -sf lib${2}GLESv1_CM.so.1 /$1/lib/libGLESv1_CM.so.1
test -f /$1/lib/lib${2}GLESv2.so.2 && ln -sf lib${2}GLESv2.so.2 /$1/lib/libGLESv2.so.2
