#!/bin/sh
#
# This file is part of HiGFXback

if [ $# != 2 ]; then
  echo Usage: $0 \"backend\" \"implementation\"
  exit 1
fi

test -f /$1/lib/lib${2}gbm.so.1 && ln -sf lib${2}gbm.so.1 /$1/lib/libgbm.so.1
