#!/bin/sh
#
# This file is part of HiGFXback

killall -9 dfbterm fbpad kmscon weston Xorg 2>/dev/null

REQUIRES="kmscon-build"

PKG_CONFIG_PATH=/drm/share/pkgconfig pkg-config --exists --print-errors $REQUIRES || return

drmdevice >/dev/null || { echo DRM device required; return 1; }

RENDERER=${RENDERER:-bbulk}

export PATH=/bin:/drm/bin

set -- -c 'export PS1="\e[0;32mkmscon>\e[0m "; exec sh'
kmscon --render-engine $RENDERER --xkb-layout fr -l /bin/sh -- "$@"
