#!/bin/sh

killall -9 dfbterm fbpad kmscon weston Xorg 2> /dev/null

REQUIRES="ttf-bitstream-vera-build twm-build xdpyinfo-build xf86-input-evdev-build xf86-video-fbdev-build xkbcomp-build xterm-build"

PKG_CONFIG_PATH=/x11/share/pkgconfig pkg-config --exists xf86-video-modesetting-build && REQUIRES="$REQUIRES xf86-video-modesetting-build"

PKG_CONFIG_PATH=/x11/share/pkgconfig pkg-config --exists --print-errors $REQUIRES || return

install -d /x11/var/log

test $DDX && rm -f /x11/etc/X11/xorg.conf

if [ ! -f /x11/etc/X11/xorg.conf ]; then
  DDX=${DDX-fbdev}
  KEYBOARD=/dev/input/`cat /proc/bus/input/devices | awk '/Handlers=/{ handler = $0 }/EV=120013/{ print handler; exit }' | grep -o event[0-9]*`
  POINTER=/dev/input/`cat /proc/bus/input/devices | awk '/Handlers=/{ handler = $0 }/EV=(7|17|1f)/{ print handler; exit }' | grep -o event[0-9]*`
  install -d /x11/etc/X11
  cat > /x11/etc/X11/xorg.conf << EOF
Section "Device"
  Identifier "card"
  Driver     "$DDX"
  BusID      "0"
EndSection

Section "InputDevice"
  Identifier "keyboard"
  Driver     "evdev"
  Option     "Device" "$KEYBOARD"
  Option     "XkbLayout" "fr"
EndSection

Section "InputDevice"
  Identifier "pointer"
  Driver     "evdev"
  Option     "Device" "$POINTER"
EndSection
EOF
fi

export PATH=/bin:/x11/bin
export DISPLAY=:0
export LUA_PATH="/share/lua/5.1/?.lua;/x11/share/lua/5.1/?.lua"
export LUA_CPATH="/lib/lua/5.1/?.so;/x11/lib/lua/5.1/?.so"
export TK_LIBRARY=/x11/lib/tk8.5
export XDG_DATA_DIRS=/share

Xorg -retro -keyboard keyboard -pointer pointer &
sleep 1
twm &
sleep 1

IFS=x read WIDTH HEIGHT << EOF
`xdpyinfo | grep dimensions | grep -oE [0-9]+x[0-9]+`
EOF
WIDTH=$((WIDTH * 80 / 800))
HEIGHT=$((HEIGHT * 24 / 600))

xterm -rv -fa vera -fs 11 -geometry ${WIDTH}x${HEIGHT}+0+0 &
