#!/bin/sh
#
# This file is part of HiGFXback

killall -9 dfbterm fbpad kmscon weston Xorg 2>/dev/null

REQUIRES="bash-build kmscon-build"

PKG_CONFIG_PATH=/drm/share/pkgconfig pkg-config --exists --print-errors $REQUIRES || return

drmdevice >/dev/null || { echo DRM device required; return 1; }

export PATH=/bin:/drm/bin

kmscon --xkb-layout fr -l /bin/bash -- --rcfile <(echo "export PS1='\e[0;32mkmscon>\e[0m '")
