#!/bin/sh

killall -9 dfbterm fbpad kmscon weston Xorg 2>/dev/null

REQUIRES="fbpad-build fbset-build ft2tf-build ttf-bitstream-vera-build"

PKG_CONFIG_PATH=/fb/share/pkgconfig pkg-config --exists --print-errors $REQUIRES || return

clear

export PATH=/bin:/fb/bin

if [ ! -f /fb/share/fbpad/regular.tf ]; then
	mkdir -p /fb/share/fbpad
	ft2tf /share/fonts/truetype/VeraMo.ttf:5.5 > /fb/share/fbpad/regular.tf
fi

IFS=x read WIDTH HEIGHT << EOF
`fbset | grep ^mode | grep -oE [0-9]+x[0-9]+`
EOF
WIDTH=$((WIDTH * 720 / 800))
HEIGHT=$((HEIGHT * 432 / 600))

FBPAD_SIZE=${WIDTH}x${HEIGHT} fbpad
