#!/bin/sh
#
# This file is part of HiGFXback

killall -9 dfbterm fbpad kmscon weston Xorg 2>/dev/null

REQUIRES="weston-build"

PKG_CONFIG_PATH=/wl/share/pkgconfig pkg-config --exists --print-errors $REQUIRES || return

install -d -m 700 /tmp/xdg

test $BACKEND && rm -f /wl/etc/xdg/weston/weston.ini

if [ ! -f /wl/etc/xdg/weston/weston.ini ]; then
	BACKEND=${BACKEND-fbdev}
	install -d /wl/etc/xdg/weston
	cat > /wl/etc/xdg/weston/weston.ini <<- EOF
		[core]
		backend=$BACKEND-backend.so

		[keyboard]
		keymap_layout=fr

		[shell]
		panel-position=none
	EOF
fi

export PATH=/bin:/wl/bin
export XDG_RUNTIME_DIR=/tmp/xdg

weston --tty=7 &
sleep 1

read WIDTH HEIGHT << EOF
`weston-info | grep -A1 mode: | tail -n 1 | sed -n 's/.*width: \([0-9]*\) px, height: \([0-9]*\) px.*/\1 \2/p'`
EOF
WIDTH=$((WIDTH * 80 / 800))
HEIGHT=$((HEIGHT * 24 / 600))

weston-terminal --columns $WIDTH --rows $HEIGHT &
